### ISSUE TITLE
完整借助了代码,但是更新到sae,空白页面

### ISSUE THREAD

**Issue by ziyanziyu** [ckryo/Laravel-on-SAE-use-Qiniu#1]
看日志中,是没有捕获到track.不知道是什么原因
PHP Fatal error:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Contracts\Debug\ExceptionHandler] is not instantiable. in /data1/www/htdocs/380/xinkingsman/2/vendor/laravel/framework/src/Illuminate/Container/Container.php:752#012Stack trace:#012#0 /data1/www/htdocs/380/xinkingsman/2/vendor/laravel/framework/src/Illuminate/Container/Container.php(633): Illuminate\Container\Container->build('Illuminate\Cont...', Array)#012#1 /data1/www/htdocs/380/xinkingsman/2/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(674): Illuminate\Container\Container->make('Illuminate\Cont...', Array)#012#2 /data1/www/htdocs/380/xinkingsman/2/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(154): Illuminate\Foundation\Application->make('Illuminate\Cont...')#012#3 /data1/www/htdocs/380/xinkingsman/2/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(79): Illuminate\Foundation\Bootstrap\HandleExceptions->getExceptionHandler()#012#4 /data1/www/htdocs/380/xinkingsman/2/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->handleException(Object(Symfony\Component\Debug\Exception\FatalErrorException))#012#5 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleShutdown()#012#6 {main}#012  thrown in /data1/www/htdocs/380/xinkingsman/2/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 752  yq70

**Comment by ziyanziyu** [comment]
已解决,引导目录中的app加载顺序错误了.
